import { IProjects } from "@/interfaces/index";

export const FerasatProjects: IProjects.PersonalProjectsPayload[] = [
  {
    title: "Takafo+",
    subtitle: "Mubadala Investment Company",
    date: "2024 – Present",
    stack: [
      "Vue 3",
      "Node.js",
      "PostgreSQL",
      "OpenAI API",
      "Azure SSO",
      "WebSockets",
      "Heygen AI",
    ],
    projectType: "Enterprise · Private",
    isPrivate: true,
    slug: "takafo-plus",
    content: [
      "Enterprise Human Capital Management platform — 11 modules, 30+ user roles covering end-to-end recruiting, CRM, onboarding, succession planning, VIP referrals, talent marketplace, and Emiratization tracking.",
      "AI candidate matching, Heygen avatar interviews, real-time WebSocket notifications, Azure MSAL SSO + B2C auth, and OpenAI-powered candidate scoring.",
    ],
    links: [],
    animation: "animation-1",
    projectImages: [],
    selected: false,
  },
  {
    title: "Qudra Tech",
    subtitle: "AI Assessment Platform",
    date: "2023 – Present",
    stack: ["Vue.js", "Node.js", "OpenAI API", "PostgreSQL"],
    projectType: "Enterprise · Private",
    isPrivate: true,
    slug: "qudra-tech",
    content: [
      "AI-powered candidate assessment platform with timed test environments and automated question generation via OpenAI API.",
      "AI-driven scoring and evaluation, session security, and live exam monitoring with real-time issue resolution.",
    ],
    links: [],
    animation: "animation-2",
    projectImages: [],
    selected: false,
  },
  {
    title: "AI Avatars",
    subtitle: "Recruitment Workflows",
    date: "2023 – Present",
    stack: ["Vue.js", "Heygen API", "OpenAI", "Node.js"],
    projectType: "Enterprise · Private",
    isPrivate: true,
    slug: "ai-avatars",
    content: [
      "Interactive AI avatar interview experience integrated into recruitment workflows.",
      "Real-time live avatar powered by Heygen API with OpenAI-driven conversational intelligence for automated human-like candidate screening at scale.",
    ],
    links: [],
    animation: "animation-3",
    projectImages: [],
    selected: false,
  },
  {
    title: "Remote Work & Dawamee",
    subtitle: "UAE Enterprise Platforms",
    date: "2024 – Present",
    stack: ["Vue.js", "Node.js", "PostgreSQL", "REST APIs"],
    projectType: "Enterprise · Private",
    isPrivate: true,
    content: [
      "Remote Work portal managing distributed workforce operations across multiple UAE organisations.",
      "Dawamee attendance and workforce management system serving thousands of employees.",
    ],
    links: [],
    animation: "animation-4",
    projectImages: [],
    selected: false,
  },
  {
    title: "The95Star",
    subtitle: "Hospitality Reservation Platform",
    date: "2022 – 2023",
    stack: [
      "Vue.js",
      "Node.js",
      "PostgreSQL",
      "Stripe",
      "PayPal",
      "Braintree",
    ],
    projectType: "Client Project · Private",
    isPrivate: true,
    content: [
      "Full-stack restaurant and hospitality reservation platform with end-to-end booking flow and table/room management.",
      "Multi-gateway payment integration — Stripe, PayPal, and Braintree — with webhook-driven reconciliation and secure transactional processing.",
    ],
    links: [],
    animation: "animation-5",
    projectImages: [],
    selected: false,
  },
  {
    title: "Invoice Generator",
    subtitle: "Open Source",
    date: "2023",
    stack: ["Vue 3", "Pinia", "Tailwind CSS"],
    projectType: "Open Source · Public",
    isPrivate: false,
    slug: "invoice-generator",
    content: [
      "Browser-based invoice builder with real-time preview and PDF export.",
      "Multi-currency support and local-storage persistence.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/invoice_generated",
      },
    ],
    liveDemo: "https://github.com/mferasatali/invoice_generated",
    animation: "animation-6",
    projectImages: [],
    selected: false,
  },
  {
    title: "Learning with Us",
    subtitle: "LMS",
    date: "2022",
    stack: ["JavaScript", "Node.js", "MongoDB"],
    projectType: "Open Source · Public",
    isPrivate: false,
    content: [
      "Collaborative learning management system with video lessons, quizzes, and progress tracking.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/Learning_with_us",
      },
    ],
    liveDemo: "https://github.com/mferasatali/Learning_with_us",
    animation: "animation-7",
    projectImages: [],
    selected: false,
  },
];
