import { IProjects } from "@/interfaces/index";

/**
 * Homepage Featured Projects = items with featured: true (ordered as listed).
 * Remaining projects still routeable / listed in Labs where applicable.
 */
export const FerasatProjects: IProjects.PersonalProjectsPayload[] = [
  {
    title: "Takafo+",
    subtitle: "Mubadala Investment Company",
    date: "2024 – Present",
    stack: [
      "Vue 3",
      "Node.js",
      "PostgreSQL",
      "OpenAI API",
      "Azure SSO",
      "WebSockets",
      "Heygen AI",
    ],
    projectType: "Enterprise · Private",
    isPrivate: true,
    featured: true,
    slug: "takafo-plus",
    content: [
      "Problem: Multi-module HCM with approval chains, SSO, and AI hiring for a sovereign wealth fund.",
      "Built: Vue 3 workflows, Azure MSAL/B2C, WebSockets, OpenAI scoring, Heygen avatar interviews.",
      "Result: 11 modules · 30+ personas · production AI screening at enterprise scale.",
      "Tradeoff: Deep private delivery — architecture & impact shared via case study (no public UI).",
    ],
    links: [],
    animation: "animation-1",
    projectImages: [],
    selected: true,
  },
  {
    title: "Qudra Tech",
    subtitle: "AI Assessment Platform",
    date: "2023 – Present",
    stack: ["Vue.js", "Node.js", "OpenAI API", "PostgreSQL"],
    projectType: "Enterprise · Private",
    isPrivate: true,
    featured: true,
    slug: "qudra-tech",
    content: [
      "Problem: High-stakes exams needed secure timers, AI questions, and live proctoring.",
      "Built: Vue assessment UI + Node/OpenAI generation & scoring + WebSocket monitoring.",
      "Result: Automated Q&A generation and faster evaluation with session integrity controls.",
      "Tradeoff: Private enterprise UI — architecture & outcomes via case study.",
    ],
    links: [],
    animation: "animation-2",
    projectImages: [],
    selected: false,
  },
  {
    title: "AI Avatars",
    subtitle: "Recruitment Workflows",
    date: "2023 – Present",
    stack: ["Vue.js", "Heygen API", "OpenAI", "Node.js"],
    projectType: "Enterprise · Private",
    isPrivate: true,
    featured: true,
    slug: "ai-avatars",
    content: [
      "Problem: First-round screening didn’t scale — scheduling blocked hiring throughput.",
      "Built: Vue interview flows + Heygen live avatar + OpenAI conversation with server prompts.",
      "Result: Structured screening outputs for recruiters inside the HCM pipeline.",
      "Tradeoff: First-round automation only — final interviews stay human.",
    ],
    links: [],
    animation: "animation-3",
    projectImages: [],
    selected: false,
  },
  {
    title: "SQL Lab",
    subtitle: "Postgres Query Studio",
    date: "2026",
    stack: ["Vue 3", "Netlify Functions", "PostgreSQL", "CodeMirror"],
    projectType: "Open Source · Live",
    isPrivate: false,
    featured: true,
    slug: "sql-lab",
    content: [
      "Problem: Needed a browser Postgres workbench without installing a heavy desktop client.",
      "Built: CodeMirror editor, Netlify Functions query API, saved queries, multi-profile localStorage.",
      "Tradeoff: Credentials stay client-side — great for personal/staging, not a hosted multi-tenant SaaS.",
      "Result: Fast local/staging SQL workflows used as a daily engineering lab tool.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/sql-labs",
      },
    ],
    liveDemo: "https://sql-labs.netlify.app/",
    animation: "animation-lab-2",
    projectImages: [],
    selected: false,
  },
  {
    title: "Changelog Generator",
    subtitle: "SvelteKit Dev Tool",
    date: "2026",
    stack: ["SvelteKit", "TypeScript", "GitHub API", "Octokit"],
    projectType: "Open Source · Live",
    isPrivate: false,
    featured: true,
    slug: "changelog-generator",
    content: [
      "Problem: Writing release notes from GitHub tags was slow across personal + office accounts.",
      "Built: Multi-account switcher, tag ranges, markdown copy/download in SvelteKit.",
      "Tradeoff: Chose SvelteKit deliberately to diversify beyond Vue/React portfolio apps.",
      "Result: One-click changelogs for release workflows.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/change-log-generator",
      },
    ],
    liveDemo: "https://change-log-generator.netlify.app/",
    animation: "animation-lab-1",
    projectImages: [],
    selected: false,
  },
  {
    title: "Babul Hawaij Events",
    subtitle: "Event records & volunteers",
    date: "2026",
    stack: ["Vue 3", "Supabase", "Pinia", "Vercel"],
    projectType: "Client · Live",
    isPrivate: false,
    featured: true,
    slug: "babul-hawaij-events",
    content: [
      "Problem: Yearly event finances and volunteers lived in spreadsheets with weak role control.",
      "Built: Vue 3 + Supabase collections, expenses, volunteer manager roles, auth + RLS.",
      "Tradeoff: Free-tier Vercel/Supabase — enough for the org without custom infra.",
      "Result: Live operational app for event records and volunteer management.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/babulhawaij/babulhawaij-events",
      },
    ],
    liveDemo: "https://babulhawaij-events.vercel.app/",
    animation: "animation-lab-4",
    projectImages: [],
    selected: false,
  },
  {
    title: "Rosca — Kameeti Manager",
    subtitle: "Rotating savings groups",
    date: "2025",
    stack: ["Vue 3", "Vuetify", "Firebase", "Vercel"],
    projectType: "Open Source · Live",
    isPrivate: false,
    featured: false,
    slug: "rosca",
    content: [
      "Problem: Kameeti/ROSCA groups hard to track — members, pots, and payouts get messy.",
      "Built: Vue 3 + Vuetify UI with Firebase Firestore for real-time group math.",
      "Result: Live tool for contributions and distribution summaries.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/rosca",
      },
    ],
    liveDemo: "https://rosca-coral.vercel.app/",
    animation: "animation-lab-5",
    projectImages: [],
    selected: false,
  },
  {
    title: "AI News · Pulse Desk",
    subtitle: "Career-first AI briefing",
    date: "2026",
    stack: ["Next.js", "TypeScript", "RSS", "PWA"],
    projectType: "Open Source · Live",
    isPrivate: false,
    featured: false,
    slug: "ai-pulse-desk",
    content: [
      "Problem: AI news is noisy — needed a career-ranked morning briefing habit.",
      "Built: Next.js RSS desk with must-reads, streaks, optional Gemini explainers, PWA install.",
      "Result: Installable daily briefing for engineers.",
    ],
    links: [],
    liveDemo: "https://ai-news-live.netlify.app/",
    animation: "animation-lab-3",
    projectImages: [],
    selected: false,
  },
  {
    title: "Expense Tracker",
    subtitle: "Personal finance dashboard",
    date: "2025",
    stack: ["Vue 3", "Vuetify", "Firebase", "Chart.js"],
    projectType: "Open Source · Live",
    isPrivate: false,
    featured: false,
    slug: "expense-tracker",
    content: [
      "Problem: Wanted accounts, budgets, and charts without a heavy finance app.",
      "Built: Vue 3 + Firebase sync + Chart.js dashboards on Vercel.",
      "Result: Real-time personal finance dashboard.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/expense-tracker",
      },
    ],
    liveDemo: "https://expense-tracker-ivory-nu-92.vercel.app/",
    animation: "animation-lab-6",
    projectImages: [],
    selected: false,
  },
  {
    title: "Anything Log",
    subtitle: "Universal personal logger",
    date: "2026",
    stack: ["Angular", "Supabase", "Postgres", "GitHub Pages"],
    projectType: "Open Source · Live",
    isPrivate: false,
    featured: false,
    slug: "anything-log",
    content: [
      "Problem: Needed one private timeline for any log type — not five note apps.",
      "Built: Angular app + Supabase Auth/Postgres RLS + tags/search/CSV export.",
      "Result: Private logger hosted on GitHub Pages.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/anything-log",
      },
    ],
    liveDemo: "https://mferasatali.github.io/anything-log/",
    animation: "animation-lab-7",
    projectImages: [],
    selected: false,
  },
  {
    title: "vue-ai-chat-kit",
    subtitle: "Vue 3 AI chat kit",
    date: "2026",
    stack: ["Vue 3", "TypeScript", "npm"],
    projectType: "Open Source · npm",
    isPrivate: false,
    featured: false,
    slug: "vue-ai-chat-kit",
    content: [
      "Problem: AI chat UIs kept reinventing streaming, sessions, and suggestions per product.",
      "Built: Vue 3 kit with message feed, session sidebar, prompt suggestions, and markdown/code copy.",
      "Result: Published npm package with minimal required-key contracts.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/vue-ai-chat-kit",
      },
      {
        name: "npm",
        color: "link",
        url: "https://www.npmjs.com/package/vue-ai-chat-kit",
      },
    ],
    liveDemo: "https://www.npmjs.com/package/vue-ai-chat-kit",
    animation: "animation-lab-kit-1",
    projectImages: [],
    selected: false,
  },
  {
    title: "vue-kanban-board-kit",
    subtitle: "Vue 3 Kanban board kit",
    date: "2026",
    stack: ["Vue 3", "TypeScript", "Drag & Drop", "npm"],
    projectType: "Open Source · npm",
    isPrivate: false,
    featured: false,
    slug: "vue-kanban-board-kit",
    content: [
      "Problem: ATS, succession, and VIP referral boards needed one reusable Kanban surface.",
      "Built: Vue 3 board kit with native drag-and-drop, 9-box badges, VIP tags, and agile cards.",
      "Result: Published npm package for recruitment and planning pipelines.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/vue-kanban-board-kit",
      },
      {
        name: "npm",
        color: "link",
        url: "https://www.npmjs.com/package/vue-kanban-board-kit",
      },
    ],
    liveDemo: "https://www.npmjs.com/package/vue-kanban-board-kit",
    animation: "animation-lab-kit-2",
    projectImages: [],
    selected: false,
  },
  {
    title: "vue-custom-data-table",
    subtitle: "Vue 3 enterprise data table",
    date: "2026",
    stack: ["Vue 3", "TypeScript", "npm"],
    projectType: "Open Source · npm",
    isPrivate: false,
    featured: false,
    slug: "vue-custom-data-table",
    content: [
      "Problem: Enterprise tables needed Excel-style header filters without a heavy UI kit.",
      "Built: Vue 3 data table with column dropdown filters, sort, selection, pagination, and query mappers.",
      "Result: Published npm package for client- and server-driven tables.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/vue-custom-data-table",
      },
      {
        name: "npm",
        color: "link",
        url: "https://www.npmjs.com/package/vue-custom-data-table",
      },
    ],
    liveDemo: "https://www.npmjs.com/package/vue-custom-data-table",
    animation: "animation-lab-kit-3",
    projectImages: [],
    selected: false,
  },
  {
    title: "vue-table-filter-kit",
    subtitle: "Vue 3 table filter kit",
    date: "2026",
    stack: ["Vue 3", "TypeScript", "npm"],
    projectType: "Open Source · npm",
    isPrivate: false,
    featured: false,
    slug: "vue-table-filter-kit",
    content: [
      "Problem: Filter bars were rebuilt per list view — search, chips, presets, and API payloads.",
      "Built: Vue 3 filter kit with search, multi-type builder, active pills, presets, and query mapper.",
      "Result: Published npm package for enterprise list filtering.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/vue-table-filter-kit",
      },
      {
        name: "npm",
        color: "link",
        url: "https://www.npmjs.com/package/vue-table-filter-kit",
      },
    ],
    liveDemo: "https://www.npmjs.com/package/vue-table-filter-kit",
    animation: "animation-lab-kit-4",
    projectImages: [],
    selected: false,
  },
  {
    title: "complete-schedule",
    subtitle: "Vue 3 schedule kit",
    date: "2026",
    stack: ["Vue 3", "Schedule-X", "TypeScript", "npm"],
    projectType: "Open Source · npm",
    isPrivate: false,
    featured: false,
    slug: "complete-schedule",
    content: [
      "Problem: Interview/calendar UIs needed a shared contract across Graph events, availability, and meeting cards.",
      "Built: Vue 3 kit with calendar, slot picker, meeting card, and mappers for Graph / availability / meeting payloads.",
      "Result: Published npm package with required-key contracts and TypeScript types.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/complete-schedule",
      },
      {
        name: "npm",
        color: "link",
        url: "https://www.npmjs.com/package/complete-schedule",
      },
    ],
    liveDemo: "https://www.npmjs.com/package/complete-schedule",
    animation: "animation-lab-8",
    projectImages: [],
    selected: false,
  },
  {
    title: "Claude Duo",
    subtitle: "Two Claude Code sessions",
    date: "2026",
    stack: ["PowerShell", "Windows Terminal", "Node.js", "npm"],
    projectType: "Open Source · npm",
    isPrivate: false,
    featured: false,
    slug: "claude-duo",
    content: [
      "Problem: Switching Claude Code accounts or projects meant juggling windows and mixed config folders.",
      "Built: Windows CLI that opens two Claude Code panes in one Terminal window with isolated CLAUDE_CONFIG_DIR per account.",
      "Result: Published npm package — npx claude-duo for Personal + Work side by side.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/claude-duo",
      },
      {
        name: "npm",
        color: "link",
        url: "https://www.npmjs.com/package/claude-duo",
      },
    ],
    liveDemo: "https://www.npmjs.com/package/claude-duo",
    animation: "animation-lab-9",
    projectImages: [],
    selected: false,
  },
  {
    title: "ClearMD",
    subtitle: "Markdown viewer for Windows",
    date: "2026",
    stack: ["Electron", "React", "Vite", "VS Code"],
    projectType: "Open Source · Desktop",
    isPrivate: false,
    featured: false,
    slug: "clear-md",
    content: [
      "Problem: Needed a clean Markdown viewer for Open with / drag-drop on Windows, plus editor preview.",
      "Built: Electron + React desktop app with file associations, and a VS Code webview extension.",
      "Result: Portable/installer builds on GitHub Releases (clear-md).",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/clear-md",
      },
      {
        name: "Releases",
        color: "link",
        url: "https://github.com/mferasatali/clear-md/releases",
      },
    ],
    liveDemo: "https://github.com/mferasatali/clear-md/releases",
    animation: "animation-lab-10",
    projectImages: [],
    selected: false,
  },
  {
    title: "Remote Work & Dawamee",
    subtitle: "UAE Enterprise Platforms",
    date: "2024 – Present",
    stack: ["Vue.js", "Node.js", "PostgreSQL", "REST APIs"],
    projectType: "Enterprise · Private",
    isPrivate: true,
    featured: false,
    content: [
      "Problem: Distributed workforce ops and attendance needed reliable enterprise portals.",
      "Built: Vue/Node Remote Work portal + Dawamee attendance system.",
      "Result: Platforms serving thousands of UAE employees.",
    ],
    links: [],
    animation: "animation-4",
    projectImages: [],
    selected: false,
  },
  {
    title: "The95Star",
    subtitle: "Hospitality Reservation Platform",
    date: "2022 – 2023",
    stack: [
      "Vue.js",
      "Node.js",
      "PostgreSQL",
      "Stripe",
      "PayPal",
      "Braintree",
    ],
    projectType: "Client Project · Private",
    isPrivate: true,
    featured: false,
    content: [
      "Problem: Hospitality booking needed end-to-end reservations and payments.",
      "Built: Vue + Node booking flow with Stripe/PayPal/Braintree webhooks.",
      "Result: Production reservation + multi-gateway payment platform.",
    ],
    links: [],
    animation: "animation-5",
    projectImages: [],
    selected: false,
  },
  {
    title: "Invoice Generator",
    subtitle: "Open Source",
    date: "2023",
    stack: ["Vue 3", "Pinia", "Tailwind CSS"],
    projectType: "Open Source · Public",
    isPrivate: false,
    featured: false,
    slug: "invoice-generator",
    content: [
      "Problem: Freelancers needed a zero-backend invoice PDF tool.",
      "Built: Vue 3 + Pinia + jsPDF with localStorage persistence.",
      "Result: Client-side invoice builder on GitHub.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/invoice_generated",
      },
    ],
    animation: "animation-6",
    projectImages: [],
    selected: false,
  },
  {
    title: "Learning with Us",
    subtitle: "LMS",
    date: "2022",
    stack: ["JavaScript", "Node.js", "MongoDB"],
    projectType: "Open Source · Public",
    isPrivate: false,
    featured: false,
    content: [
      "Problem: Needed a simple collaborative LMS for lessons and quizzes.",
      "Built: Node/Mongo learning flows with progress tracking.",
      "Result: Open-source LMS starter on GitHub.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/Learning_with_us",
      },
    ],
    animation: "animation-7",
    projectImages: [],
    selected: false,
  },
];
