import { IProjects } from "@/interfaces/index";

export const FerasatProjects: IProjects.PersonalProjectsPayload[] = [
  {
    title: "Changelog Generator",
    subtitle: "SvelteKit Dev Tool",
    date: "2026",
    stack: ["SvelteKit", "TypeScript", "GitHub API", "Octokit"],
    projectType: "Open Source · Live",
    isPrivate: false,
    slug: "changelog-generator",
    content: [
      "Multi-account GitHub changelog generator — Personal/Office switch, tag ranges, markdown copy & download.",
      "Built in SvelteKit to diversify beyond Vue/React portfolio apps.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/change-log-generator",
      },
      {
        name: "Live",
        color: "link",
        url: "https://change-log-generator.netlify.app/",
      },
    ],
    liveDemo: "https://change-log-generator.netlify.app/",
    animation: "animation-lab-1",
    projectImages: [],
    selected: false,
  },
  {
    title: "SQL Lab",
    subtitle: "Postgres Query Studio",
    date: "2026",
    stack: ["Vue 3", "Netlify Functions", "PostgreSQL", "CodeMirror"],
    projectType: "Open Source · Live",
    isPrivate: false,
    slug: "sql-lab",
    content: [
      "Browser-based Postgres workbench with CodeMirror editor, Netlify Functions query API, and saved query library.",
      "Connections stay in localStorage; supports multiple profiles for local / staging / production workflows.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/sql-labs",
      },
      {
        name: "Live",
        color: "link",
        url: "https://sql-labs.netlify.app/",
      },
    ],
    liveDemo: "https://sql-labs.netlify.app/",
    animation: "animation-lab-2",
    projectImages: [],
    selected: false,
  },
  {
    title: "AI News · Pulse Desk",
    subtitle: "Career-first AI briefing",
    date: "2026",
    stack: ["Next.js", "TypeScript", "RSS", "PWA"],
    projectType: "Open Source · Live",
    isPrivate: false,
    slug: "ai-pulse-desk",
    content: [
      "Daily AI news desk with RSS ingestion, career-ranked stories, must-read list, streaks, and optional Gemini explanations.",
      "Installable PWA designed as a morning briefing habit for engineers.",
    ],
    links: [
      {
        name: "Live",
        color: "link",
        url: "https://ai-news-live.netlify.app/",
      },
    ],
    liveDemo: "https://ai-news-live.netlify.app/",
    animation: "animation-lab-3",
    projectImages: [],
    selected: false,
  },
  {
    title: "Babul Hawaij Events",
    subtitle: "Event records & volunteers",
    date: "2026",
    stack: ["Vue 3", "Supabase", "Pinia", "Vercel"],
    projectType: "Client · Live",
    isPrivate: false,
    slug: "babul-hawaij-events",
    content: [
      "Yearly event collections, expense tracking, and volunteer manager roles on Vue 3 + Supabase.",
      "Auth, Postgres, and storage on a free Vercel + Supabase stack.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/babulhawaij/babulhawaij-events",
      },
      {
        name: "Live",
        color: "link",
        url: "https://babulhawaij-events.vercel.app/",
      },
    ],
    liveDemo: "https://babulhawaij-events.vercel.app/",
    animation: "animation-lab-4",
    projectImages: [],
    selected: false,
  },
  {
    title: "Rosca — Kameeti Manager",
    subtitle: "Rotating savings groups",
    date: "2025",
    stack: ["Vue 3", "Vuetify", "Firebase", "Vercel"],
    projectType: "Open Source · Live",
    isPrivate: false,
    slug: "rosca",
    content: [
      "Manage Kameeti/ROSCA groups — members, monthly pot calculations, contributions, and distribution summaries.",
      "Vue 3 + Vuetify UI with Firebase Firestore for real-time group data.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/rosca",
      },
      {
        name: "Live",
        color: "link",
        url: "https://rosca-coral.vercel.app/",
      },
    ],
    liveDemo: "https://rosca-coral.vercel.app/",
    animation: "animation-lab-5",
    projectImages: [],
    selected: false,
  },
  {
    title: "Expense Tracker",
    subtitle: "Personal finance dashboard",
    date: "2025",
    stack: ["Vue 3", "Vuetify", "Firebase", "Chart.js"],
    projectType: "Open Source · Live",
    isPrivate: false,
    slug: "expense-tracker",
    content: [
      "Track accounts, expenses, income, and monthly budgets with Chart.js dashboards.",
      "Firebase-backed real-time sync, hosted on Vercel.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/expense-tracker",
      },
      {
        name: "Live",
        color: "link",
        url: "https://expense-tracker-ivory-nu-92.vercel.app/",
      },
    ],
    liveDemo: "https://expense-tracker-ivory-nu-92.vercel.app/",
    animation: "animation-lab-6",
    projectImages: [],
    selected: false,
  },
  {
    title: "Takafo+",
    subtitle: "Mubadala Investment Company",
    date: "2024 – Present",
    stack: [
      "Vue 3",
      "Node.js",
      "PostgreSQL",
      "OpenAI API",
      "Azure SSO",
      "WebSockets",
      "Heygen AI",
    ],
    projectType: "Enterprise · Private",
    isPrivate: true,
    slug: "takafo-plus",
    content: [
      "Enterprise Human Capital Management platform — 11 modules, 30+ user roles covering end-to-end recruiting, CRM, onboarding, succession planning, VIP referrals, talent marketplace, and Emiratization tracking.",
      "AI candidate matching, Heygen avatar interviews, real-time WebSocket notifications, Azure MSAL SSO + B2C auth, and OpenAI-powered candidate scoring.",
    ],
    links: [],
    animation: "animation-1",
    projectImages: [],
    selected: false,
  },
  {
    title: "Qudra Tech",
    subtitle: "AI Assessment Platform",
    date: "2023 – Present",
    stack: ["Vue.js", "Node.js", "OpenAI API", "PostgreSQL"],
    projectType: "Enterprise · Private",
    isPrivate: true,
    slug: "qudra-tech",
    content: [
      "AI-powered candidate assessment platform with timed test environments and automated question generation via OpenAI API.",
      "AI-driven scoring and evaluation, session security, and live exam monitoring with real-time issue resolution.",
    ],
    links: [],
    animation: "animation-2",
    projectImages: [],
    selected: false,
  },
  {
    title: "AI Avatars",
    subtitle: "Recruitment Workflows",
    date: "2023 – Present",
    stack: ["Vue.js", "Heygen API", "OpenAI", "Node.js"],
    projectType: "Enterprise · Private",
    isPrivate: true,
    slug: "ai-avatars",
    content: [
      "Interactive AI avatar interview experience integrated into recruitment workflows.",
      "Real-time live avatar powered by Heygen API with OpenAI-driven conversational intelligence for automated human-like candidate screening at scale.",
    ],
    links: [],
    animation: "animation-3",
    projectImages: [],
    selected: false,
  },
  {
    title: "Remote Work & Dawamee",
    subtitle: "UAE Enterprise Platforms",
    date: "2024 – Present",
    stack: ["Vue.js", "Node.js", "PostgreSQL", "REST APIs"],
    projectType: "Enterprise · Private",
    isPrivate: true,
    content: [
      "Remote Work portal managing distributed workforce operations across multiple UAE organisations.",
      "Dawamee attendance and workforce management system serving thousands of employees.",
    ],
    links: [],
    animation: "animation-4",
    projectImages: [],
    selected: false,
  },
  {
    title: "The95Star",
    subtitle: "Hospitality Reservation Platform",
    date: "2022 – 2023",
    stack: [
      "Vue.js",
      "Node.js",
      "PostgreSQL",
      "Stripe",
      "PayPal",
      "Braintree",
    ],
    projectType: "Client Project · Private",
    isPrivate: true,
    content: [
      "Full-stack restaurant and hospitality reservation platform with end-to-end booking flow and table/room management.",
      "Multi-gateway payment integration — Stripe, PayPal, and Braintree — with webhook-driven reconciliation and secure transactional processing.",
    ],
    links: [],
    animation: "animation-5",
    projectImages: [],
    selected: false,
  },
  {
    title: "Invoice Generator",
    subtitle: "Open Source",
    date: "2023",
    stack: ["Vue 3", "Pinia", "Tailwind CSS"],
    projectType: "Open Source · Public",
    isPrivate: false,
    slug: "invoice-generator",
    content: [
      "Browser-based invoice builder with real-time preview and PDF export.",
      "Multi-currency support and local-storage persistence.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/invoice_generated",
      },
    ],
    liveDemo: "https://github.com/mferasatali/invoice_generated",
    animation: "animation-6",
    projectImages: [],
    selected: false,
  },
  {
    title: "Learning with Us",
    subtitle: "LMS",
    date: "2022",
    stack: ["JavaScript", "Node.js", "MongoDB"],
    projectType: "Open Source · Public",
    isPrivate: false,
    content: [
      "Collaborative learning management system with video lessons, quizzes, and progress tracking.",
    ],
    links: [
      {
        name: "GitHub",
        color: "link",
        url: "https://github.com/mferasatali/Learning_with_us",
      },
    ],
    liveDemo: "https://github.com/mferasatali/Learning_with_us",
    animation: "animation-7",
    projectImages: [],
    selected: false,
  },
];
