import { IJourney } from "@/interfaces/index";

export const FerasatSkillCategories: IJourney.SkillCategory[] = [
  {
    name: "Languages",
    variant: "languages",
    skills: ["JavaScript", "TypeScript", "Python", "C++"],
  },
  {
    name: "Frontend",
    variant: "frontend",
    skills: [
      "Vue.js 3",
      "Nuxt.js",
      "React.js",
      "Next.js 14",
      "Angular 17",
      "Svelte",
      "Tailwind CSS",
      "Vuetify",
      "HTML/CSS/SASS",
      "GSAP",
      "D3.js",
      "Pinia",
      "Vuex",
      "Redux",
      "RxJS",
      "NgRx",
    ],
  },
  {
    name: "Backend",
    variant: "backend",
    skills: [
      "Node.js",
      "Express.js",
      "NestJS",
      "Laravel/PHP",
      "REST APIs",
      "GraphQL",
      "Webhooks",
      "Microservices",
    ],
  },
  {
    name: "Databases",
    variant: "databases",
    skills: [
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Redis",
      "Sequelize",
      "Mongoose",
      "Supabase",
      "pgvector",
    ],
  },
  {
    name: "AI / LLM",
    variant: "ai",
    skills: [
      "RAG Pipelines",
      "LangChain",
      "LlamaIndex",
      "OpenAI API",
      "GPT-4 / Claude / Gemini",
      "Pinecone",
      "Weaviate",
      "Embeddings",
      "Prompt Engineering",
      "AI Agents",
      "Semantic Search",
      "Heygen Avatar AI",
    ],
  },
  {
    name: "Cloud & Tools",
    variant: "cloud",
    skills: [
      "AWS",
      "Azure",
      "Heroku",
      "Docker",
      "CI/CD",
      "GitHub Actions",
      "Stripe",
      "PayPal",
      "Braintree",
    ],
  },
];

export const FerasatSkillsFlat = FerasatSkillCategories.flatMap((c) => c.skills);
